name: automated_testing_framework_plugin_strings
description: Library to use provide string generation and maipulation capabilities to the testing framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_strings

version: 4.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  automated_testing_framework: ^4.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  intl: ^0.17.0
  json_class: ^2.1.2+4
  json_theme: ^4.0.0
  logging: ^1.0.2
  static_translations: ^2.1.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
