name: 'automated_testing_framework_plugin_strings'
description: 'Library to use provide string generation and maipulation capabilities to the testing framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_strings'
version: '4.0.1+3'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  automated_testing_framework: '^5.0.0+3'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.2.0+6'
  intl: '^0.18.0'
  json_class: '^2.1.5+2'
  json_theme: '^5.0.0+2'
  logging: '^1.1.1'
  static_translations: '^2.1.2+3'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
